/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/fish2.glb --output src/components/models/Fish2.tsx --types 
*/

import { useGLTF } from '@react-three/drei'

export default function Fish2(props: any) {
  const { nodes, materials } = useGLTF('/models/fish2.glb') as any

  if (!nodes || !materials) {
    return null
  }

  return (
    <group {...props} dispose={null}>
      {/* 缩小 0.5 倍，旋转使嘴部向上，使用默认材质 */}
      <mesh 
        geometry={nodes['tripo_node_a763bd53-000e-494e-8d1b-57e6db21b8b4'].geometry} 
        material={materials['tripo_mat_a763bd53-000e-494e-8d1b-57e6db21b8b4']}
        castShadow
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.5}
      />
    </group>
  )
}

useGLTF.preload('/models/fish2.glb')
