/*
  Tuft of grass 
  by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) 
  via Poly Pizza (https://poly.pizza/m/3tyh15Fbmsx)

  Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Instance, Instances, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useMemo, useRef } from 'react'
import { BufferGeometry, Mesh } from 'three'
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js'
import type { Position } from '../../utils/position'
import type { Rotation } from '../../utils/rotation'

export interface GrassInstanceProps {
  position: Position
  rotation: Rotation
  scale: number | [number, number, number]
}

export interface InstancedGrassProps {
  count?: number
  instances: GrassInstanceProps[]
}

export default function InstancedGrass({ count = 10, instances }: InstancedGrassProps) {
  const { scene, materials } = useGLTF('./models/grass.glb')
  const instancesRef = useRef<any>(null)

  const geometry = useMemo(() => {
    const geometries: BufferGeometry[] = []
    scene.traverse(child => {
      if (child instanceof Mesh) {
        const g = child.geometry.clone()
        g.applyMatrix4(child.matrixWorld)
        geometries.push(g)
      }
    })
    return mergeGeometries(geometries).center()
  }, [scene])

  // 风吹动画效果
  useFrame(({ clock }) => {
    if (!instancesRef.current) return
    
    const time = clock.elapsedTime
    const windSpeed = 0.5
    const windStrength = 0.3
    
    instances.current.forEach((instance: any, i: number) => {
      // 每株草有不同的相位，创造自然的随机效果
      const phase = i * 0.1
      const windX = Math.sin(time * windSpeed + phase) * windStrength
      const windZ = Math.cos(time * windSpeed * 0.7 + phase) * windStrength * 0.5
      
      // 在原始位置基础上添加风吹偏移
      const originalProps = instances[i]
      instance.position.set(
        originalProps.position.x,
        originalProps.position.y,
        originalProps.position.z
      )
      instance.rotation.set(
        originalProps.rotation.x + windX * 0.3,
        originalProps.rotation.y,
        originalProps.rotation.z + windZ
      )
      instance.scale.set(
        Array.isArray(originalProps.scale) ? originalProps.scale[0] : originalProps.scale,
        Array.isArray(originalProps.scale) ? originalProps.scale[1] : originalProps.scale,
        Array.isArray(originalProps.scale) ? originalProps.scale[2] : originalProps.scale
      )
    })
  })

  return (
    <Instances
      ref={instancesRef}
      castShadow
      receiveShadow
      geometry={geometry}
      material={materials._crayfishdiffuse}
      limit={count}
    >
      {instances.map((props, i) => (
        // @ts-expect-error Quaternion is a valid rotation type
        <Instance key={`grass-${i}`} {...props} />
      ))}
    </Instances>
  )
}

useGLTF.preload('./models/grass.glb')
